services:
  db.mealmanager:
    image: 'postgres:13.1-alpine'
    container_name: mm-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
  rabbitmq.mealmanager:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  localstack:
    container_name: "localstack_main"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-5000}:${PORT_WEB_UI-5000}"
    environment:
      - AWS_REGION=us-east-1
      - DATA_DIR=${DATA_DIR- }
      - DEBUG=${DEBUG- }
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=${PORT_WEB_UI-9000}
      - SERVICES=ses,s3,iam
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volumes/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./volumes/docker-entrypoint-initaws.d:/docker-entrypoint-initaws.d"
  hoster:
    container_name: hoster
    image: dvdarias/docker-hoster
    volumes:
      - /etc/hosts:/tmp/hosts
      - /run/docker.sock:/tmp/docker.sock
