version: '3.5'

services:
  db.mealmanager:
    image: 'postgres:13.1-alpine'
    container_name: mm-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mealmanager
  rabbitmq.mealmanager:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mealmanager
  api.mealmanager:
    image: 'mjourard/mealmanager-api:latest'
    container_name: mm-api
    ports:
      - 8080:8080
    environment:
      - AWS_SES_REGION=${AWS_SES_REGION}
      - AWS_SMTP_USERNAME=${AWS_SMTP_USERNAME}
      - AWS_SMTP_PASSWORD=${AWS_SMTP_PASSWORD}
      - MEALMANAGER_EMAIL_FROM=${MEALMANAGER_EMAIL_FROM}
      - DB_HOST=db.mealmanager
      - DB_PORT=5432
      - CORS_ALLOWED_ORIGIN=http://client.mealmanager
      - RABBITMQ_HOST=rabbitmq.mealmanager
      - RABBITMQ_PORT=5672
    depends_on:
      - rabbitmq.mealmanager
      - db.mealmanager
    networks:
      - mealmanager
  client.mealmanager:
    image: 'mjourard/mealmanager-client:latest'
    container_name: mm-client
    ports:
      - 80:80
    networks:
      - mealmanager
  hoster:
    container_name: hoster
    image: dvdarias/docker-hoster
    volumes:
      - /etc/hosts:/tmp/hosts
      - /run/docker.sock:/tmp/docker.sock
    networks:
      - mealmanager

volumes:
  pgdata:

networks:
  mealmanager:
    name: mealmanager