# fly.toml - Fly.io configuration for Meal Manager API
app = "meal-manager"
primary_region = "yul"

[build]
  dockerfile = "Dockerfile.fly"

[env]
  SERVER_PORT = "8080"
  SPRING_PROFILES_ACTIVE = "prod"
  DB_HOST = "meal-manager-db.flycast"
  DB_PORT = "5432"
  DB_NAME = "meal_manager"
  DB_QUERY_PARAMS = "?sslmode=disable"
  RABBITMQ_HOST = "meal-manager-mq.internal"
  RABBITMQ_PORT = "5672"
  MEALMANAGER_EMAIL_FROM = "no-reply@mealmanager.org"
  CORS_ALLOWED_ORIGIN = "https://mealmanager.org"
  AWS_SES_REGION = "us-east-1"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[http_service.ports]]
    handlers = ["http"]
    port = 80

  [[http_service.ports]]
    handlers = ["tls", "http"]
    port = 443

[checks]
  [checks.health]
    port = 8080
    type = "http"
    interval = "10s"
    timeout = "2s"
    grace_period = "30s"
    method = "GET"
    path = "/api/healthcheck"
    protocol = "http"

[metrics]
  port = 8080
  path = "/actuator/prometheus" 